from __future__ import annotations

from lib import SHELL, read


def register(s) -> None:
    audio = read(SHELL / "services" / "Audio.qml")
    pop = read(SHELL / "modules" / "popouts" / "AudioPop.qml")
    s.has("audio sinks", audio, "readonly property var sinks")
    s.has("audio sources", audio, "readonly property var sources")
    s.has("audio setSink", audio, "function setSink")
    s.has("audio setSource", audio, "function setSource")
    s.has("audio deviceName", audio, "function deviceName")
    s.has("audio preferred sink", audio, "preferredDefaultAudioSink")
    s.has("audio preferred source", audio, "preferredDefaultAudioSource")
    s.has("audio live default", audio, "wpctl")
    s.has("audio set-default", audio, "set-default")
    s.has("audio track devices", audio, "!n.isStream")
    s.has("audio hide headphone sink", audio, "function hideSink")
    s.has("audio hide jack mic", audio, "function hideSource")
    s.has("audio headphone jack", audio, "headphone")
    s.has("audio stereo jack mic", audio, "stereo microphone")
    s.has("audio hide empty hdmi", audio, "hdmi")
    s.has("audio generic hdmi nick", audio, "[2-9]")
    s.has("audio sinks skip hidden", audio, "!hideSink(n)")
    s.has("audio sources skip hidden", audio, "!hideSource(n)")
    s.has("mixer sink list", pop, "Audio.sinks")
    s.has("mixer source list", pop, "Audio.sources")
    s.has("mixer pick sink", pop, "Audio.setSink")
    s.has("mixer pick source", pop, "Audio.setSource")
    s.has("mixer device name", pop, "Audio.deviceName")
    s.has("mixer still streams", pop, "Audio.streams")
    s.has("mixer still mute", pop, "Audio.toggleMute")
    s.has("mixer still mic", pop, "Audio.toggleMicMute")
    s.has("mixer still volume", pop, "Audio.setVolume")
    s.ok("mixer wider than 260", "implicitWidth: 280" in pop or "implicitWidth: 300" in pop)
