from __future__ import annotations

from lib import SHELL, read


def register(s) -> None:
    src = read(SHELL / "modules" / "launcher" / "Launcher.qml")
    s.has("launcher WheelHandler", src, "WheelHandler")
    s.has("launcher nudgeList", src, "function nudgeList")
    s.has("launcher down nudge", src, "Keys.onDownPressed: win.nudgeList(1)")
    s.has("launcher up nudge", src, "Keys.onUpPressed: win.nudgeList(-1)")
    s.has("launcher enter", src, "Keys.onEnterPressed: win.activate()")
    s.has("launcher return", src, "Keys.onReturnPressed: win.activate()")
    s.has("launcher escape", src, "Keys.onEscapePressed")
    s.has("launcher browse", src, "property bool browse")
    s.has("launcher rest card", src, "RestCard")
    s.has("launcher calc prefix", src, 'startsWith("=")')
    s.has("launcher clip prefix", src, 'startsWith(";")')
    s.has("launcher web prefix", src, 'startsWith("?")')
    s.has("launcher act prefix", src, 'startsWith("/")')
    s.has("launcher music prefix", src, 'startsWith("@")')
    s.has("launcher activate app", src, 'row.kind === "app"')
    s.has("launcher execute", src, "entry.execute")
    s.has("launcher namespace", src, 'WlrLayershell.namespace: "tanjun-launcher"')
    s.has("launcher key prime", src, "KeyPrime")
    prime = read(SHELL / "modules" / "widgets" / "KeyPrime.qml")
    s.has("key prime exclusive", prime, "WlrKeyboardFocus.Exclusive")
    s.has("key prime ondemand", prime, "WlrKeyboardFocus.OnDemand")
    s.has("key prime 75ms", prime, "interval: 75")
    rest = read(SHELL / "modules" / "launcher" / "RestCard.qml")
    s.has("rest clock", rest, "Time.time")
    s.has("rest weather", rest, "Weather.text")
    s.has("rest player", rest, "PlayerCard")
    s.has("rest hint apps", rest, '"apps"')
    s.has("rest hint calc", rest, '"calc"')
    s.has("rest hint clips", rest, '"clips"')
    s.has("rest hint web", rest, '"web"')
    s.has("rest hint act", rest, '"act"')
    s.has("rest hint music", rest, '"music"')
    s.has("nudge from rest", src, "win.browse = true")
    s.has("nudge back rest", src, "win.browse = false")
    s.has("list not interactive", src, "interactive: false")
