from __future__ import annotations

from lib import COMP, ROOT, SHELL, bash_array, read


def register(s) -> None:
    host = read(SHELL / "modules" / "widgets" / "OverlayHost.qml")
    keys = read(SHELL / "modules" / "widgets" / "KeyCatcher.qml")
    settings = read(SHELL / "modules" / "settings" / "Settings.qml")
    clip = read(SHELL / "modules" / "clipboard" / "Clipboard.qml")
    overview = read(SHELL / "modules" / "overview" / "Overview.qml")
    card = read(SHELL / "modules" / "overview" / "OverviewCard.qml")
    audio_pop = read(SHELL / "modules" / "popouts" / "AudioPop.qml")
    net_pop = read(SHELL / "modules" / "popouts" / "NetPop.qml")
    audio = read(SHELL / "services" / "Audio.qml")
    idle = read(SHELL / "services" / "Idle.qml")
    polkit = read(SHELL / "modules" / "polkit" / "PolkitAsk.qml")
    shell = read(SHELL / "shell.qml")
    qmldir = read(SHELL / "services" / "qmldir")
    hypr_auto = read(COMP / "hyprland" / "modules" / "autostart.lua")
    niri_auto = read(COMP / "niri" / "config" / "autostart.kdl")
    niri_bind = read(COMP / "niri" / "config" / "keybinds.kdl")
    hypr_reload = read(COMP / "hyprland" / "scripts" / "reload-shell.sh")
    niri_reload = read(COMP / "niri" / "scripts" / "reload-shell.sh")
    key_prime = read(SHELL / "modules" / "widgets" / "KeyPrime.qml")
    comp = read(SHELL / "services" / "Compositor.qml")

    s.has("overlay host bar hole", host, "Intersection.Xor")
    s.has("overlay host key prime", host, "KeyPrime")
    s.has("overlay host dismiss twin", host, "tanjun-pop-away")
    s.has("overlay host layer name", host, "layerName")
    s.has("key catcher before item", keys, "Keys.BeforeItem")
    s.has("key catcher hjkl", keys, "Qt.Key_J")
    s.has("key catcher enter", keys, "Qt.Key_Return")
    s.has("key prime hold exclusive", key_prime, "holdExclusive")

    s.has("settings overlay host", settings, "OverlayHost")
    s.has("clipboard overlay host", clip, "OverlayHost")
    s.has("overview overlay host", overview, "OverlayHost")
    s.lacks("overview no hypr import", overview, "import Quickshell.Hyprland")
    s.has("overview card capture", card, "client.capture")
    s.has("compositor windows", comp, "host.windows")
    s.has("compositor setDpms", comp, "function setDpms")
    s.has("compositor refreshWindows", comp, "function refreshWindows")

    s.has("mixer key catcher", audio_pop, "KeyCatcher")
    s.has("net key catcher", net_pop, "KeyCatcher")

    s.has("audio port available", audio, "port.available")
    s.has("audio attached", audio, "function attached")
    s.has("audio node ready", audio, "node.ready")

    s.has("idle monitor", idle, "IdleMonitor")
    s.has("idle dim 120", idle, "timeout: 120")
    s.has("idle lock 300", idle, "timeout: 300")
    s.has("idle dpms 600", idle, "timeout: 600")
    s.has("idle suspend 900", idle, "timeout: 900")
    s.has("idle hibernate 1800", idle, "timeout: 1800")
    s.has("idle lock request", idle, "Lock.request")
    s.has("idle dpms", idle, "Compositor.setDpms")
    s.has("qmldir Idle", qmldir, "singleton Idle")
    s.has("shell arms idle", shell, "Idle.watching")

    s.has("polkit agent", polkit, "PolkitAgent")
    s.has("polkit overlay", polkit, "OverlayHost")
    s.has("shell polkit", shell, "PolkitAsk")

    s.lacks("hypr autostart no hypridle", hypr_auto, "hypridle")
    s.lacks("hypr autostart no polkit-gnome", hypr_auto, "polkit-gnome")
    s.lacks("niri autostart no idle.sh", niri_auto, "idle.sh")
    s.lacks("niri autostart no polkit-gnome", niri_auto, "polkit-gnome")
    s.has("niri tab overview ipc", niri_bind, "toggleOverview")
    s.lacks("hypr reload no hypridle", hypr_reload, "hypridle")
    s.lacks("niri reload no swayidle", niri_reload, "swayidle")
    s.lacks("niri reload no idle.sh", niri_reload, "idle.sh")
    s.has("hypr autostart hyprsunset", hypr_auto, "hyprsunset")
    s.has("niri autostart quickshell", niri_auto, "quickshell")
    setup = read(ROOT / "scripts" / "setup.sh")
    pkgs = (
        bash_array(setup, "PKGS_COMMON")
        + bash_array(setup, "PKGS_HYPR")
        + bash_array(setup, "PKGS_NIRI")
    )
    for dead in ("hypridle", "hyprlock", "swayidle", "polkit-gnome"):
        s.ok(f"setup pkgs omit {dead}", dead not in pkgs)
