auth required pam_faillock.so preauth silent deny=5 unlock_time=300
auth sufficient pam_unix.so try_first_pass
auth [default=die] pam_faillock.so authfail deny=5 unlock_time=300
auth sufficient pam_faillock.so authsucc
account required pam_unix.so
